/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * 정션의 API 명세서
 * API 명세서
 * OpenAPI spec version: v1
 */

/**
 * 퀴즈 보기에 사용되는 선택지 응답 DTO
 */
export type ChoiceResDTO = {
  /** 단어 선택지 즉 오답애들 */
  dummyWord?: string;
};
