/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * 정션의 API 명세서
 * API 명세서
 * OpenAPI spec version: v1
 */

/**
 * 클립 영상 응답 DTO
 */
export type ClipVideoResDTO = {
  /** 영상 URL */
  videoUrl?: string;
};
