/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * 정션의 API 명세서
 * API 명세서
 * OpenAPI spec version: v1
 */
import type { ClipVideoResDTO } from './clipVideoResDTO';

/**
 * 클립 목록 응답 DTO
 */
export type ClipResDTO = {
  /** 클립에 저장된 영상 개수 */
  videoCnt?: number;
  /** 클립에 저장된 영상 리스트 */
  clipVideoResList?: ClipVideoResDTO[];
};
