/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * 정션의 API 명세서
 * API 명세서
 * OpenAPI spec version: v1
 */

/**
 * 마이페이지 응답 DTO
 */
export type GetMyPageResDTO = {
  /** 사용자 이름 */
  name?: string;
  /** 사용자 프로필 이미지 URL */
  profile?: string;
  /** 사용자 이메일 */
  email?: string;
};
