/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * 정션의 API 명세서
 * API 명세서
 * OpenAPI spec version: v1
 */

/**
 * 영상 저장 요청 DTO
 */
export type PostVideoReqDTO = {
  /** 저장할 영상 ID */
  videoId?: number;
};
