/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * 정션의 API 명세서
 * API 명세서
 * OpenAPI spec version: v1
 */

export type RandomQuizVideoType = typeof RandomQuizVideoType[keyof typeof RandomQuizVideoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RandomQuizVideoType = {
  SYNONYM: 'SYNONYM',
  BLANK: 'BLANK',
  "": "",
} as const;
