/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * 정션의 API 명세서
 * API 명세서
 * OpenAPI spec version: v1
 */

/**
 * 영상 타입
 */
export type RandomQuizDTOVideoType = typeof RandomQuizDTOVideoType[keyof typeof RandomQuizDTOVideoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RandomQuizDTOVideoType = {
  SYNONYM: 'SYNONYM',
  BLANK: 'BLANK',
  "": "",
} as const;
