/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * 정션의 API 명세서
 * API 명세서
 * OpenAPI spec version: v1
 */

/**
 * 홈 화면 랜덤 영상 응답 DTO
 */
export type RandomHomeResDTO = {
  /** 영상 URL */
  videoUrl?: string;
  /** 영상과 관련된 대화/스크립트 */
  chat?: string;
  /** 최승호 */
  name?: string;
  /** 프로필 이미지 */
  profile?: string;
};
