/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * 정션의 API 명세서
 * API 명세서
 * OpenAPI spec version: v1
 */
import type { RandomQuizVideoType } from './randomQuizVideoType';

export type RandomQuizParams = {
videoType: RandomQuizVideoType;
};
