/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * 정션의 API 명세서
 * API 명세서
 * OpenAPI spec version: v1
 */
import type { S3ImageBodyVideoType } from './s3ImageBodyVideoType';

export type S3ImageBody = {
  video: Blob;
  name: string;
  compareWord: string;
  successWord: string;
  caption: string;
  videoType: S3ImageBodyVideoType;
  sentence: string;
};
