/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * 정션의 API 명세서
 * API 명세서
 * OpenAPI spec version: v1
 */

export type S3ImageBodyVideoType = typeof S3ImageBodyVideoType[keyof typeof S3ImageBodyVideoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const S3ImageBodyVideoType = {
  SYNONYM: 'SYNONYM',
  BLANK: 'BLANK',
  "": "",
} as const;
