/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * 정션의 API 명세서
 * API 명세서
 * OpenAPI spec version: v1
 */
import type { VocaResDTO } from './vocaResDTO';

/**
 * 사용자의 단어 목록 응답 DTO
 */
export type VocaSelectResDTO = {
  /** 저장된 단어 개수 */
  vocaSize?: number;
  /** 단어 응답 리스트 */
  vocaResList?: VocaResDTO[];
};
