/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * 정션의 API 명세서
 * API 명세서
 * OpenAPI spec version: v1
 */

/**
 * AI가 생성한 단어 응답 DTO
 */
export type VocaAIResDTO = {
  /** 단어 원문 */
  word?: string;
  /** 예시 문장 (줄바꿈으로 3개) */
  exampleSentence?: string;
  /** 유의어 (줄바꿈으로 3개) */
  synonym?: string;
  /** 발음 */
  pronunciation?: string;
  /** 한국어 해석 */
  meaning?: string;
  /** 단어 유형 */
  vocaType?: string;
};
