/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * 정션의 API 명세서
 * API 명세서
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetMyPageResDTO
} from '../../model';





/**
 * 사용자 정보 데이터를 줍니다.
 * @summary 사용자 정보 조회
 */
export const getMyPage = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetMyPageResDTO>> => {
    
    
    return axios.get(
      `/api/user/mypage`,options
    );
  }


export const getGetMyPageQueryKey = () => {
    return [`/api/user/mypage`] as const;
    }

    
export const getGetMyPageQueryOptions = <TData = Awaited<ReturnType<typeof getMyPage>>, TError = AxiosError<GetMyPageResDTO | GetMyPageResDTO>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyPage>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyPageQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyPage>>> = ({ signal }) => getMyPage({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyPage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyPageQueryResult = NonNullable<Awaited<ReturnType<typeof getMyPage>>>
export type GetMyPageQueryError = AxiosError<GetMyPageResDTO | GetMyPageResDTO>


export function useGetMyPage<TData = Awaited<ReturnType<typeof getMyPage>>, TError = AxiosError<GetMyPageResDTO | GetMyPageResDTO>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyPage>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyPage>>,
          TError,
          Awaited<ReturnType<typeof getMyPage>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyPage<TData = Awaited<ReturnType<typeof getMyPage>>, TError = AxiosError<GetMyPageResDTO | GetMyPageResDTO>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyPage>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyPage>>,
          TError,
          Awaited<ReturnType<typeof getMyPage>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyPage<TData = Awaited<ReturnType<typeof getMyPage>>, TError = AxiosError<GetMyPageResDTO | GetMyPageResDTO>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyPage>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 사용자 정보 조회
 */

export function useGetMyPage<TData = Awaited<ReturnType<typeof getMyPage>>, TError = AxiosError<GetMyPageResDTO | GetMyPageResDTO>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyPage>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyPageQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



